package dataTransfer;

public enum CSVInfo
{

    LANGUAGE, CLASS_LIST, YOUTUBE, DOC, WEB, CLASS_INFO_LIST, CLASS_INFO_GEN, FIELD_LIST, METHOD_LIST, CONST_LIST, SUB_PROMPT, SUB_INFO, EX_CODE, LINK,

    FROM_FIELDS, FROM_METHODS, FROM_CONSTS

}
